#!/bin/sh /etc/rc.common
START=95
USE_PROCD=1
start_service() {
	[ "$(uci -q get rviprobe.config.enabled)" = "0" ] && return 0
	procd_open_instance
	procd_set_param command /usr/lib/rvi-probe/agent.sh
	procd_set_param respawn 300 5 5
	procd_close_instance
}
stop_service() { :; }
reload_service() { stop; start; }
