name = "rvi-provision"
main = "src/worker.ts"
compatibility_date = "2025-09-01"

[vars]
# Example for local development; use wrangler secret to set real values
# CF_API_TOKEN   = "REPLACE_WITH_YOUR_TOKEN"   # scopes: Account Tunnel:Edit, Zone DNS:Edit
# CF_ACCOUNT_ID  = "REPLACE_WITH_ACCOUNT_ID"
# CF_ZONE_ID     = "REPLACE_WITH_ZONE_ID"      # zone for nomadconnect.app
# BASE_HOST      = "nomadconnect.app"          # optional override
