name = "rvi-provision"
main = "src/worker.ts"
compatibility_date = "2025-09-01"

[vars]
# Runtime vars should be set via Cloudflare dashboard or wrangler secrets
# CF_API_TOKEN   - secret; scopes: Account Tunnel:Edit, Zone DNS:Edit
# CF_ACCOUNT_ID  - your Cloudflare account ID
# CF_ZONE_ID     - zone for nomadconnect.app
# BASE_HOST      - optional override for base domain (default nomadconnect.app)
