# A descriptive name for the workflow
name: Build and Deploy OpenWrt IPK Package

# --- Triggers ---
# This workflow runs on a push to specific paths or when manually dispatched
on:
  push:
    paths:
      - 'package/rvi-probe/**'
      - '.github/workflows/build-ipk.yml'
  workflow_dispatch:

# --- Jobs ---
# A single job named 'build' will run
jobs:
  build:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest

    # Environment variables available to all steps in this job
    env:
      R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
      R2_BUCKET: ${{ secrets.R2_BUCKET }}
      R2_PUBLIC_BASE: ${{ secrets.R2_PUBLIC_BASE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: auto

    # --- Steps ---
    # The sequence of tasks to be executed
    steps:
      - name:  Checkout Repository
        uses: actions/checkout@v4

      - name: Install AWS CLI v2
        run: |
          set -euxo pipefail
          curl -fsSL https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
          unzip -q awscliv2.zip
          sudo ./aws/install --update

      - name: Prepare Package Files
        run: |
          set -euxo pipefail
          # Create the staging directories
          mkdir -p build/CONTROL build/data
          
          # Copy all package files into the data directory
          echo "Copying package files..."
          rsync -a package/rvi-probe/root/ build/data/
          
          # Set executable permissions on scripts
          echo "Setting file permissions..."
          find build/data -path "*/bin/*" -type f -exec chmod 755 {} +
          find build/data -path "*/sbin/*" -type f -exec chmod 755 {} +
          find build/data -path "*/init.d/*" -type f -exec chmod 755 {} +
          find build/data -path "*/cgi-bin/*" -type f -exec chmod 755 {} +
          find build/data -name "*.sh" -type f -exec chmod 755 {} +

      - name: Create Control Files
        run: |
          set -euxo pipefail
          # Create the main 'control' file with package metadata
          cat > build/CONTROL/control <<'EOC'
          Package: rvi-probe
          Version: 0.5.0-2
          Architecture: all
          Maintainer: RVInternetHelp <support@rvinternethelp.com>
          Section: net
          Priority: optional
          Depends: curl, ca-bundle, ca-certificates, jq, ip-full, ubus, uclient-fetch, iwinfo, wireless-tools, openssl-util
          Description: RVInternetHelp Network Probe
           Support/diagnostics agent with outage checks, speed tests,
           Cloudflare tunnel share code, JSON status, cell metrics, and CRM hooks.
          EOC

          # Copy optional maintainer scripts (preinst, postinst, etc.) if they exist
          for f in preinst postinst prerm postrm; do
            if [ -f "package/rvi-probe/CONTROL/$f" ]; then
              install -m 755 "package/rvi-probe/CONTROL/$f" "build/CONTROL/$f"
            fi
          done

      - name: Build the IPK Archive
        run: |
          set -euxo pipefail
          cd build
          
          # Create the mandatory debian-binary file
          echo "2.0" > debian-binary
          
          # Create the control and data tarballs
          tar --owner=0 --group=0 --numeric-owner -czf control.tar.gz -C CONTROL *
          tar --owner=0 --group=0 --numeric-owner -czf data.tar.gz -C data *
          
          # Combine the components into the final .ipk file using 'ar'
          ar -cr rvi-probe_0.5.0-2_all.ipk debian-binary control.tar.gz data.tar.gz
          
          echo "--- IPK File Details ---"
          ls -la rvi-probe_0.5.0-2_all.ipk
          file rvi-probe_0.5.0-2_all.ipk
          echo "IPK package built successfully ✅"

      - name: Generate Package Index
        run: |
          set -euxo pipefail
          cd build
          
          # Get metadata from the generated IPK
          SIZE=$(stat -c%s rvi-probe_0.5.0-2_all.ipk)
          MD5=$(md5sum rvi-probe_0.5.0-2_all.ipk | cut -d' ' -f1)
          SHA256=$(sha256sum rvi-probe_0.5.0-2_all.ipk | cut -d' ' -f1)
          
          # Create the 'Packages' file for the opkg repository
          cat > Packages <<EOP
          Package: rvi-probe
          Version: 0.5.0-2
          Architecture: all
          Maintainer: RVInternetHelp <support@rvinternethelp.com>
          Section: net
          Priority: optional
          Depends: curl, ca-bundle, ca-certificates, jq, ip-full, ubus, uclient-fetch, iwinfo, wireless-tools, openssl-util
          Description: RVInternetHelp Network Probe
           Support/diagnostics agent with outage checks, speed tests,
           Cloudflare tunnel share code, JSON status, cell metrics, and CRM hooks.
          Filename: rvi-probe_0.5.0-2_all.ipk
          Size: $SIZE
          MD5Sum: $MD5
          SHA256sum: $SHA256
          EOP
          
          # Create the gzipped version of the index
          gzip -fk9 Packages
          echo "--- Repository Index Files ---"
          ls -la *.ipk Packages*

      - name: Upload to Cloudflare R2
        run: |
          set -euxo pipefail
          cd build
          ENDPOINT="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
          
          echo "Uploading package, index, and gzipped index to R2..."
          aws s3 cp rvi-probe_0.5.0-2_all.ipk "s3://${R2_BUCKET}/openwrt/23.05/" --endpoint-url "$ENDPOINT"
