name: Build rvi-probe IPK (fast, no SDK)

on:
  push:
    branches: [ main ]
    paths:
      - 'package/**'
      - '.github/workflows/build-ipk.yml'
      - 'scripts/**'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get opkg-utils (from OpenWrt repo)
        run: |
          git clone --depth=1 https://github.com/openwrt/opkg-utils.git
          chmod +x opkg-utils/*

      - name: Install packager deps
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot tar gzip findutils coreutils

      - name: Assemble package root
        run: |
          SRC="package/rvi-probe/files"
          PKG="dist/pkg"
          mkdir -p "$PKG"
          cp -a "$SRC"/. "$PKG"/

          # CONTROL/control
          mkdir -p "$PKG/CONTROL"
          printf '%s\n' \
            'Package: rvi-probe' \
            'Version: 0.5.0-1' \
            'Architecture: all' \
            'Maintainer: RVInternetHelp <support@rvinternethelp.com>' \
            'Section: utils' \
            'Priority: optional' \
            'Depends: curl, ca-bundle, ca-certificates, jq, ip-full, ubus, uclient-fetch, iwinfo, wireless-tools, openssl-util' \
            'Source: local' \
            'Description: RVInternetHelp Network Probe (SupportLink UI, JSON status, cell metrics, speed tests). Post-install auto-configures loopback uHTTPd and (if present) cloudflared.' \
            > "$PKG/CONTROL/control"

          # Ensure CONTROL scripts are executable
          if [ -d "$PKG/CONTROL" ]; then
            chmod 0755 "$PKG/CONTROL/"* || true
          fi

      - name: Build .ipk with ipkg-build
        run: |
          mkdir -p dist/repo
          OPKG="./opkg-utils"
          fakeroot "${OPKG}/ipkg-build" -o root -g root dist/pkg dist/repo
          ls -l dist/repo

      - name: Generate opkg index
        run: |
          OPKG="./opkg-utils"
          cd dist/repo
          "${OPKG}/opkg-make-index" . > Packages
          gzip -9kf Packages
          ls -l

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rvi-probe-ipk
          path: dist/repo/*

  publish:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      SIGNING_ENABLED: ${{ vars.SIGNING_ENABLED }}
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: rvi-probe-ipk
          path: dist/repo

      - name: Install awscli v2 & usign
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip usign
          curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: Sign Packages index (optional)
        if: env.SIGNING_ENABLED == '1'
        env:
          USIGN_PRIVATE_KEY_BASE64: ${{ secrets.USIGN_PRIVATE_KEY_BASE64 }}
        run: |
          mkdir -p package-signing
          echo "$USIGN_PRIVATE_KEY_BASE64" | base64 -d > package-signing/usign-private.key
          chmod 600 package-signing/usign-private.key
          cd dist/repo
          usign -S -m Packages -s ../../package-signing/usign-private.key -x Packages.sig
          ls -l

      - name: Publish to Cloudflare R2
        env:
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET: ${{ secrets.R2_BUCKET }}
          R2_PUBLIC_BASE: ${{ secrets.R2_PUBLIC_BASE }}
        run: |
          ENDPOINT="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
          aws configure set aws_access_key_id "$R2_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$R2_SECRET_ACCESS_KEY"

          # Upload repo (ipk + Packages + Packages.gz [+ Packages.sig if present])
          aws s3 cp dist/repo "s3://${R2_BUCKET}/openwrt/23.05/" \
            --endpoint-url "$ENDPOINT" --recursive --acl public-read --content-type application/octet-stream

          # Fix content-type for Packages.gz
          if [ -f dist/repo/Packages.gz ]; then
            aws s3 cp dist/repo/Packages.gz "s3://${R2_BUCKET}/openwrt/23.05/Packages.gz" \
              --endpoint-url "$ENDPOINT" --acl public-read --content-type application/gzip --metadata-directive REPLACE
          fi

          echo "Published to: ${R2_PUBLIC_BASE}/openwrt/23.05/"