name: Build librespeed-cli for OpenWrt arches
on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-librespeed.yml'

jobs:
  build-upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - arch_name: mips_24kc         # OpenWrt arch folder name (X750)
            goos: linux
            goarch: mipsle              # Go arch for 24kc (little endian)
            extra_env: GOMIPS=softfloat # no FPU on 24kc
          - arch_name: aarch64_cortex-a53 # OpenWrt arch folder name (Filogic/X3000)
            goos: linux
            goarch: arm64
            extra_env: ""
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
            go-version: '1.22.x'

      - name: Build librespeed-cli (${{ matrix.target.arch_name }})
        env:
          GOOS: ${{ matrix.target.goos }}
          GOARCH: ${{ matrix.target.goarch }}
          GOMIPS: ${{ matrix.target.extra_env == 'GOMIPS=softfloat' && 'softfloat' || '' }}
          CGO_ENABLED: 0
        run: |
          # Fetch official CLI
          git clone --depth=1 https://github.com/librespeed/speedtest-cli.git
          cd speedtest-cli
          # Build statically, small
          go build -trimpath -ldflags="-s -w" -o librespeed-cli .
          file librespeed-cli
          mkdir -p dist/librespeed/${{ matrix.target.arch_name }}
          mv librespeed-cli dist/librespeed/${{ matrix.target.arch_name }}/librespeed-cli
          sha256sum dist/librespeed/${{ matrix.target.arch_name }}/librespeed-cli > dist/librespeed/${{ matrix.target.arch_name }}/SHA256SUMS

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: librespeed-${{ matrix.target.arch_name }}
          path: dist/librespeed/${{ matrix.target.arch_name }}/*

      - name: Publish to Cloudflare R2
        env:
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET: ${{ secrets.R2_BUCKET }}
          R2_PUBLIC_BASE: ${{ secrets.R2_PUBLIC_BASE }}
        run: |
          sudo apt-get update && sudo apt-get install -y awscli
          ENDPOINT="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
          aws configure set aws_access_key_id "$R2_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$R2_SECRET_ACCESS_KEY"
          aws s3 cp dist/librespeed "s3://${R2_BUCKET}/librespeed/23.05/" \
            --endpoint-url "$ENDPOINT" --recursive --acl public-read --content-type application/octet-stream
          echo "Published to: ${R2_PUBLIC_BASE}/librespeed/23.05/"
