name: Build rvi-probe IPK

on:
  push:
    paths:
      - 'package/rvi-probe/**'
      - '.github/workflows/build-ipk.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
      R2_BUCKET: ${{ secrets.R2_BUCKET }}
      R2_PUBLIC_BASE: ${{ secrets.R2_PUBLIC_BASE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: auto
    steps:
      - uses: actions/checkout@v4

      - name: Install AWS CLI v2
        run: |
          set -euxo pipefail
          curl -fsSL https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
          unzip -q awscliv2.zip
          sudo ./aws/install --update

      - name: Create IPK package manually
        run: |
          set -euxo pipefail
          VER="0.5.0-4"
          mkdir -p build/{CONTROL,data}
          # Copy from files/ (OpenWrt-style repo tree)
          if [ ! -d package/rvi-probe/files ]; then
            echo "ERROR: package/rvi-probe/files does not exist."
            exit 1
          fi
          rsync -a package/rvi-probe/files/ build/data/
          # Sanity check: ensure at least 1 regular file
          FILECOUNT=$(find build/data -type f | wc -l | tr -d ' ')
          if [ "$FILECOUNT" -lt 1 ]; then
            echo "ERROR: No files found to package. Aborting."
            find package/rvi-probe -maxdepth 3 -print
            exit 1
          fi
          # Ensure common script paths are executable (idempotent)
          find build/data -path "*/bin/*" -type f -exec chmod 755 {} +
          find build/data -path "*/sbin/*" -type f -exec chmod 755 {} +
          find build/data -path "*/init.d/*" -type f -exec chmod 755 {} +
          find build/data -path "*/cgi-bin/*" -type f -exec chmod 755 {} +
          find build/data -name "*.sh" -type f -exec chmod 755 {} +
          # CONTROL/control
          cat > build/CONTROL/control <<EOC
          Package: rvi-probe
          Version: ${VER}
          Architecture: all
          Maintainer: RVInternetHelp <support@rvinternethelp.com>
          Section: net
          Priority: optional
          Depends: curl, ca-bundle, ca-certificates, jq, ip-full, ubus, uclient-fetch, iwinfo, wireless-tools, openssl-util
          Description: RVInternetHelp Network Probe
           Support/diagnostics agent with outage checks, speed tests,
           Cloudflare tunnel share code, JSON status, cell metrics, and CRM hooks.
          EOC
          # Maintainer scripts: prefer stamped postinst.in if present
          for f in preinst prerm postrm; do
            if [ -f package/rvi-probe/files/CONTROL/$f ]; then
              install -m 755 package/rvi-probe/files/CONTROL/$f build/CONTROL/$f
            fi
          done
          if [ -f package/rvi-probe/files/CONTROL/postinst.in ]; then
            sed "s/__VER__/${VER}/g" package/rvi-probe/files/CONTROL/postinst.in > build/CONTROL/postinst
            chmod 755 build/CONTROL/postinst
          elif [ -f package/rvi-probe/files/CONTROL/postinst ]; then
            install -m 755 package/rvi-probe/files/CONTROL/postinst build/CONTROL/postinst
          fi
          cd build
          echo "2.0" > debian-binary
          tar --owner=0 --group=0 --numeric-owner -czf control.tar.gz -C CONTROL .
          tar --owner=0 --group=0 --numeric-owner -czf data.tar.gz -C data .
          # EXTRA VALIDATION: list contents
          echo "=== control.tar.gz ==="; tar -tzf control.tar.gz
          echo "=== data.tar.gz (should list your files) ==="; tar -tzf data.tar.gz
          # Fail if data archive is tiny
          DATASIZE=$(stat -c%s data.tar.gz)
          if [ "$DATASIZE" -lt 100 ]; then
            echo "ERROR: data.tar.gz is too small; likely empty."
            exit 1
          fi
          ar -cr rvi-probe_${VER}_all.ipk debian-binary control.tar.gz data.tar.gz
          ls -la rvi-probe_${VER}_all.ipk
          file rvi-probe_${VER}_all.ipk
          echo "IPK package built successfully"

      - name: Create clean package index
        run: |
          set -euxo pipefail
          cd build
          VER="0.5.0-4"
          SIZE=$(stat -c%s rvi-probe_${VER}_all.ipk)
          MD5=$(md5sum rvi-probe_${VER}_all.ipk | cut -d' ' -f1)
          SHA256=$(sha256sum rvi-probe_${VER}_all.ipk | cut -d' ' -f1)
          cat > Packages <<EOP
          Package: rvi-probe
          Version: ${VER}
          Architecture: all
          Maintainer: RVInternetHelp <support@rvinternethelp.com>
          Section: net
          Priority: optional
          Depends: curl, ca-bundle, ca-certificates, jq, ip-full, ubus, uclient-fetch, iwinfo, wireless-tools, openssl-util
          Description: RVInternetHelp Network Probe
           Support/diagnostics agent with outage checks, speed tests,
           Cloudflare tunnel share code, JSON status, cell metrics, and CRM hooks.
          Filename: rvi-probe_${VER}_all.ipk
          Size: $SIZE
          MD5Sum: $MD5
          SHA256sum: $SHA256
          EOP
          grep -n '^Package:' Packages
          gzip -fk9 Packages
          ls -la *.ipk Packages*

      - name: Upload to Cloudflare R2
        run: |
          set -euxo pipefail
          cd build
          VER="0.5.0-4"; ENDPOINT="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
          aws s3 cp Packages "s3://${R2_BUCKET}/openwrt/23.05/" --endpoint-url "$ENDPOINT" --acl public-read --content-type text/plain --cache-control 'no-store'
          aws s3 cp Packages.gz "s3://${R2_BUCKET}/openwrt/23.05/" --endpoint-url "$ENDPOINT" --acl public-read --content-type application/gzip --cache-control 'no-store'
          aws s3 cp rvi-probe_${VER}_all.ipk "s3://${R2_BUCKET}/openwrt/23.05/" --endpoint-url "$ENDPOINT" --acl public-read --content-type application/octet-stream --cache-control 'no-store' --metadata-directive REPLACE

      - name: Verify upload
        if: ${{ env.AWS_ACCESS_KEY_ID != '' && env.AWS_SECRET_ACCESS_KEY != '' }}
        run: |
          set -euxo pipefail
          curl -fI "${R2_PUBLIC_BASE}/openwrt/23.05/Packages"
          curl -fI "${R2_PUBLIC_BASE}/openwrt/23.05/Packages.gz"
          curl -fI "${R2_PUBLIC_BASE}/openwrt/23.05/rvi-probe_0.5.0-4_all.ipk" | tee /tmp/ipk_headers
          grep -i '^cache-control: no-store' /tmp/ipk_headers
