name: Build librespeed-cli

on:
  push:
    paths:
      - '.github/workflows/build-librespeed.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: mips_24kc
            goarch: mipsle
            gomips: softfloat
          - arch: aarch64_cortex-a53
            goarch: arm64
            gomips: ""
    env:
      R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
      R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      R2_BUCKET: ${{ secrets.R2_BUCKET }}
      AWS_DEFAULT_REGION: auto
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install AWS CLI v2
        run: |
          set -euxo pipefail
          curl -fsSL https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
          unzip -q awscliv2.zip
          sudo ./aws/install

      - name: Build librespeed-cli
        env:
          GOOS: linux
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
          GOMIPS: ${{ matrix.gomips }}
        run: |
          set -euxo pipefail
          curl -fsSL https://codeload.github.com/librespeed/speedtest-cli/tar.gz/refs/heads/master | tar -xz
          cd speedtest-cli-*
          go build -trimpath -ldflags="-s -w" -o librespeed-cli
          mkdir -p "$GITHUB_WORKSPACE/dist/${{ matrix.arch }}"
          cp librespeed-cli "$GITHUB_WORKSPACE/dist/${{ matrix.arch }}/"
          cd "$GITHUB_WORKSPACE/dist/${{ matrix.arch }}"
          sha256sum librespeed-cli > SHA256SUMS
          test -s librespeed-cli
          test -s SHA256SUMS

      - name: Upload to R2
        run: |
          set -euxo pipefail
          ENDPOINT="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
          aws s3 cp "dist/${{ matrix.arch }}/librespeed-cli" "s3://${R2_BUCKET}/librespeed/23.05/${{ matrix.arch }}/" --endpoint-url "$ENDPOINT" --acl public-read
          aws s3 cp "dist/${{ matrix.arch }}/SHA256SUMS" "s3://${R2_BUCKET}/librespeed/23.05/${{ matrix.arch }}/" --endpoint-url "$ENDPOINT" --acl public-read