name: Build rvi-probe IPK

on:
  workflow_dispatch:
  push:
    paths:
      - 'package/rvi-probe/**'
      - '.github/workflows/build-ipk.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # ---- App config ----
      PKG_VERSION: 0.5.0-6     # <— bump when you publish
      PKG_NAME: rvi-probe

      # ---- R2 / AWS creds ----
      R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
      R2_BUCKET: ${{ secrets.R2_BUCKET }}
      R2_PUBLIC_BASE: ${{ secrets.R2_PUBLIC_BASE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: auto

    steps:
      - uses: actions/checkout@v4

      - name: Install build tools (awscli, binutils, zstd)
        run: |
          set -euxo pipefail
          sudo apt-get update -y
          sudo apt-get install -y binutils zstd
          curl -fsSL https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
          unzip -q awscliv2.zip
          sudo ./aws/install --update

      - name: Create IPK package
        run: |
          set -euxo pipefail

          NAME="${PKG_NAME}"
          VER="${PKG_VERSION}"
          OUT="${NAME}_${VER}_all.ipk"

          # Clean build
          rm -rf build
          mkdir -p build/{CONTROL,data}

          echo "=== Copying files (exclude CONTROL from data) ==="
          # Copy top-level entries under package/rvi-probe/files (etc, usr, www, etc.)
          find package/rvi-probe/files -maxdepth 1 -mindepth 1 -not -name CONTROL -print0 | xargs -0 -I {} cp -a {} build/data/

          # Verify files copied
          FILECOUNT=$(find build/data -type f | wc -l)
          echo "Files copied: $FILECOUNT"
          if [ "$FILECOUNT" -eq 0 ]; then
            echo "ERROR: No files copied!"
            exit 1
          fi

          # Set permissions
          find build/data -path "*/bin/*" -type f -exec chmod 755 {} + || true
          find build/data -path "*/init.d/*" -type f -exec chmod 755 {} + || true
          find build/data -path "*/cgi-bin/*" -type f -exec chmod 755 {} + || true
          find build/data -name "*.sh" -type f -exec chmod 755 {} + || true

          # Create control file
          cat > build/CONTROL/control <<EOC
          Package: ${NAME}
          Version: ${VER}
          Architecture: all
          Maintainer: RVInternetHelp <support@rvinternethelp.com>
          Section: net
          Priority: optional
          Depends: curl, ca-bundle, ca-certificates, jq, ip-full, ubus, uclient-fetch, iwinfo, wireless-tools, openssl-util
          Description: RVInternetHelp Network Probe
           Support/diagnostics agent with outage checks, speed tests,
           Cloudflare tunnel share code, JSON status, cell metrics, and CRM hooks.
          EOC

          # Copy maintainer scripts (optional)
          for f in preinst postinst prerm postrm; do
            if [ -f package/rvi-probe/files/CONTROL/$f ]; then
              install -m 755 package/rvi-probe/files/CONTROL/$f build/CONTROL/$f
            fi
          done

          cd build

          # Create IPK members
          echo "2.0" > debian-binary
          tar --owner=0 --group=0 --numeric-owner -czf control.tar.gz -C CONTROL .

          # Create data archive
          cd data
          tar --owner=0 --group=0 --numeric-owner -czf ../data.tar.gz .
          cd ..

          # Verify data archive
          DATASIZE=$(stat -c%s data.tar.gz)
          echo "Data archive size: $DATASIZE bytes"
          echo "Files in archive: $(tar -tzf data.tar.gz | wc -l)"
          if [ "$DATASIZE" -lt 50 ]; then
            echo "ERROR: data.tar.gz too small"
            exit 1
          fi

          # Create IPK
          ar -cr "${OUT}" debian-binary control.tar.gz data.tar.gz
          echo "IPK created successfully:"
          ls -la "${OUT}"

      - name: Verify rvi-probe IPK payload (payload gate)
        run: |
          set -euo pipefail
          cd build

          IPK="$(ls -1 ${PKG_NAME}_${PKG_VERSION}_all.ipk)"
          echo "Inspecting $IPK"
          mkdir -p /tmp/ipkcheck && cd /tmp/ipkcheck
          ar -x "$GITHUB_WORKSPACE/build/$IPK"

          COUNT=0
          if [ -f data.tar.gz ]; then
            echo "Found data.tar.gz; showing first 50 entries:"
            tar -tzf data.tar.gz | sed -n '1,50p'
            COUNT="$(tar -tzf data.tar.gz | grep -vE '^\./?$' | wc -l)"
          elif [ -f data.tar.zst ]; then
            echo "Found data.tar.zst; decompressing"
            zstd -dq data.tar.zst
            echo "Showing first 50 entries:"
            tar -tf data.tar | sed -n '1,50p'
            COUNT="$(tar -tf data.tar | grep -vE '^\./?$' | wc -l)"
          else
            echo "ERROR: No data.tar.* in IPK"
            exit 1
          fi

          echo "Payload file count: $COUNT"
          MIN_FILES=7   # init, 3 usr/bin helpers, 2 lib scripts, 2 cgi, etc. Adjust if needed.
          if [ "$COUNT" -lt "$MIN_FILES" ]; then
            echo "ERROR: IPK payload too small (empty or directories only)"
            exit 1
          fi

          echo "Payload looks good ✅"

      - name: Create package index
        run: |
          set -euxo pipefail
          cd build

          IPK="${PKG_NAME}_${PKG_VERSION}_all.ipk"
          SIZE=$(stat -c%s "$IPK")
          MD5=$(md5sum "$IPK" | cut -d' ' -f1)
          SHA256=$(sha256sum "$IPK" | cut -d' ' -f1)

          echo "Package stats: Size=$SIZE, MD5=$MD5"

          cat > Packages <<EOF
          Package: ${PKG_NAME}
          Version: ${PKG_VERSION}
          Architecture: all
          Maintainer: RVInternetHelp <support@rvinternethelp.com>
          Section: net
          Priority: optional
          Depends: curl, ca-bundle, ca-certificates, jq, ip-full, ubus, uclient-fetch, iwinfo, wireless-tools, openssl-util
          Description: RVInternetHelp Network Probe
           Support/diagnostics agent with outage checks, speed tests,
           Cloudflare tunnel share code, JSON status, cell metrics, and CRM hooks.
          Filename: ${IPK}
          Size: $SIZE
          MD5Sum: $MD5
          SHA256sum: $SHA256

          EOF

          gzip -fk9 Packages

      - name: Upload to Cloudflare R2
        if: ${{ success() }}
        run: |
          set -euxo pipefail
          cd build
          ENDPOINT="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"

          echo "Uploading to Cloudflare R2..."
          aws s3 cp Packages "s3://${R2_BUCKET}/openwrt/23.05/" \
            --endpoint-url "$ENDPOINT" --acl public-read \
            --content-type text/plain --cache-control 'no-cache, no-store, must-revalidate' \
            --metadata-directive REPLACE

          aws s3 cp Packages.gz "s3://${R2_BUCKET}/openwrt/23.05/" \
            --endpoint-url "$ENDPOINT" --acl public-read \
            --content-type application/gzip --cache-control 'no-cache, no-store, must-revalidate' \
            --metadata-directive REPLACE

          IPK="${PKG_NAME}_${PKG_VERSION}_all.ipk"
          aws s3 cp "$IPK" "s3://${R2_BUCKET}/openwrt/23.05/" \
            --endpoint-url "$ENDPOINT" --acl public-read \
            --content-type application/octet-stream --cache-control 'no-cache, no-store, must-revalidate' \
            --metadata-directive REPLACE
          echo "Upload complete!"

      - name: Verify upload
        if: ${{ success() }}
        run: |
          set -euxo pipefail
          echo "Waiting briefly for CDN propagation..."
          sleep 5
          curl -fI "${R2_PUBLIC_BASE}/openwrt/23.05/Packages"
          curl -fI "${R2_PUBLIC_BASE}/openwrt/23.05/${PKG_NAME}_${PKG_VERSION}_all.ipk"
          echo "Build and upload complete - version ${PKG_VERSION} ready for installation"
