name: Build rvi-probe IPK

on:
  workflow_dispatch:
  push:
    paths:
      - 'package/rvi-probe/**'
      - '.github/workflows/build-ipk.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
      R2_BUCKET: ${{ secrets.R2_BUCKET }}
      R2_PUBLIC_BASE: ${{ secrets.R2_PUBLIC_BASE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: auto
    steps:
      - uses: actions/checkout@v4

      - name: Install AWS CLI v2
        run: |
          curl -fsSL https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
          unzip -q awscliv2.zip
          sudo ./aws/install --update

      - name: Create IPK package
        run: |
          set -euxo pipefail
          
          # Clean build
          rm -rf build
          mkdir -p build/{CONTROL,data}

          echo "=== Copying files (exclude CONTROL from data) ==="
          find package/rvi-probe/files -maxdepth 1 -mindepth 1 -not -name CONTROL -print0 | xargs -0 -I {} cp -r {} build/data/
          
          # Verify files copied
          FILECOUNT=$(find build/data -type f | wc -l)
          echo "Files copied: $FILECOUNT"
          if [ "$FILECOUNT" -eq 0 ]; then
            echo "ERROR: No files copied!"
            exit 1
          fi

          # Set permissions
          find build/data -path "*/bin/*" -type f -exec chmod 755 {} + || true
          find build/data -path "*/init.d/*" -type f -exec chmod 755 {} + || true
          find build/data -path "*/cgi-bin/*" -type f -exec chmod 755 {} + || true
          find build/data -name "*.sh" -type f -exec chmod 755 {} + || true

          # Create control file
          cat > build/CONTROL/control <<'EOC'
          Package: rvi-probe
          Version: 0.5.0-5
          Architecture: all
          Maintainer: RVInternetHelp <support@rvinternethelp.com>
          Section: net
          Priority: optional
          Depends: curl, ca-bundle, ca-certificates, jq, ip-full, ubus, uclient-fetch, iwinfo, wireless-tools, openssl-util
          Description: RVInternetHelp Network Probe
           Support/diagnostics agent with outage checks, speed tests,
           Cloudflare tunnel share code, JSON status, cell metrics, and CRM hooks.
          EOC

          # Copy maintainer scripts
          for f in preinst postinst prerm postrm; do
            if [ -f package/rvi-probe/files/CONTROL/$f ]; then
              install -m 755 package/rvi-probe/files/CONTROL/$f build/CONTROL/$f
            fi
          done

          cd build

          # Create IPK archives
          echo "2.0" > debian-binary
          tar --owner=0 --group=0 --numeric-owner -czf control.tar.gz -C CONTROL .
          
          # Create data archive using the working method
          cd data
          tar --owner=0 --group=0 --numeric-owner -czf ../data.tar.gz .
          cd ..

          # Verify data archive
          DATASIZE=$(stat -c%s data.tar.gz)
          echo "Data archive size: $DATASIZE bytes"
          echo "Files in archive: $(tar -tzf data.tar.gz | wc -l)"
          
          if [ "$DATASIZE" -lt 50 ]; then
            echo "ERROR: data.tar.gz too small"
            exit 1
          fi

          # Create IPK
          ar -cr rvi-probe_0.5.0-5_all.ipk debian-binary control.tar.gz data.tar.gz
          
          echo "IPK created successfully:"
          ls -la rvi-probe_0.5.0-5_all.ipk

      - name: Create package index
        run: |
          set -euxo pipefail
          cd build
          
          SIZE=$(stat -c%s rvi-probe_0.5.0-5_all.ipk)
          MD5=$(md5sum rvi-probe_0.5.0-5_all.ipk | cut -d' ' -f1)
          SHA256=$(sha256sum rvi-probe_0.5.0-5_all.ipk | cut -d' ' -f1)
          
          echo "Package stats: Size=$SIZE, MD5=$MD5"
          
          cat > Packages <<EOF
          Package: rvi-probe
          Version: 0.5.0-5
          Architecture: all
          Maintainer: RVInternetHelp <support@rvinternethelp.com>
          Section: net
          Priority: optional
          Depends: curl, ca-bundle, ca-certificates, jq, ip-full, ubus, uclient-fetch, iwinfo, wireless-tools, openssl-util
          Description: RVInternetHelp Network Probe
           Support/diagnostics agent with outage checks, speed tests,
           Cloudflare tunnel share code, JSON status, cell metrics, and CRM hooks.
          Filename: rvi-probe_0.5.0-5_all.ipk
          Size: $SIZE
          MD5Sum: $MD5
          SHA256sum: $SHA256

          EOF
          
          gzip -fk9 Packages

      - name: Upload to Cloudflare R2
        run: |
          set -euxo pipefail
          cd build
          
          ENDPOINT="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
          
          echo "Uploading to Cloudflare R2..."
          
          # Upload package index
          aws s3 cp Packages "s3://${R2_BUCKET}/openwrt/23.05/" \
            --endpoint-url "$ENDPOINT" --acl public-read \
            --content-type text/plain --cache-control 'no-cache, no-store, must-revalidate' \
            --metadata-directive REPLACE
            
          aws s3 cp Packages.gz "s3://${R2_BUCKET}/openwrt/23.05/" \
            --endpoint-url "$ENDPOINT" --acl public-read \
            --content-type application/gzip --cache-control 'no-cache, no-store, must-revalidate' \
            --metadata-directive REPLACE
            
          # Upload IPK package
          aws s3 cp rvi-probe_0.5.0-5_all.ipk "s3://${R2_BUCKET}/openwrt/23.05/" \
            --endpoint-url "$ENDPOINT" --acl public-read \
            --content-type application/octet-stream --cache-control 'no-cache, no-store, must-revalidate' \
            --metadata-directive REPLACE
            
          echo "Upload complete!"

      - name: Verify upload
        run: |
          set -euxo pipefail
          
          echo "Waiting for CDN propagation..."
          sleep 5
          
          echo "Verifying uploaded files..."
          curl -fI "${R2_PUBLIC_BASE}/openwrt/23.05/Packages" || echo "Package index verification failed"
          curl -fI "${R2_PUBLIC_BASE}/openwrt/23.05/rvi-probe_0.5.0-5_all.ipk" || echo "IPK verification failed"
          
          echo "Build and upload complete - version 0.5.0-5 ready for installation"
